# Generated by Django 3.1.2 on 2022-03-22 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Prowebfase4App', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DB_multimedia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Series', models.FileField(upload_to='')),
                ('Peliculas', models.FileField(upload_to='')),
                ('Animes', models.FileField(upload_to='')),
            ],
        ),
    ]
