# Generated by Django 3.1.2 on 2022-03-30 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DB_multimedia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Series', models.FileField(upload_to='')),
                ('Peliculas', models.FileField(upload_to='')),
                ('Animes', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='login',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Correo_Electronico', models.EmailField(max_length=254)),
                ('Contraseña', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='usuarios_fservicios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Usuario', models.CharField(max_length=26)),
                ('Clave_especial_de_usuario', models.IntegerField(max_length=11)),
                ('Correo_Electronico', models.EmailField(max_length=254)),
                ('Locacion', models.BooleanField(verbose_name=True)),
                ('Servicio', models.BooleanField(verbose_name=True)),
            ],
        ),
    ]
